<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ST.DotNetSolutionKit.Samples.Orders\ST.DotNetSolutionKit.Samples.Orders.csproj" />
      <ProjectReference Include="..\..\..\common\ST.DotNetSolutionKit.Samples.Common\ST.DotNetSolutionKit.Samples.Common.csproj" />
      <ProjectReference Include="..\..\..\common\ST.DotNetSolutionKit.Samples.Common.Application\ST.DotNetSolutionKit.Samples.Common.Application.csproj" />
      <ProjectReference Include="..\..\..\common\ST.DotNetSolutionKit.Samples.Common.Infrastructure\ST.DotNetSolutionKit.Samples.Common.Infrastructure.csproj" />
      <ProjectReference Include="..\ST.DotNetSolutionKit.Samples.Orders.Application\ST.DotNetSolutionKit.Samples.Orders.Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>ST.DotNetSolutionKit.Samples.Orders.Tests</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" />
        <PackageReference Include="Hangfire.Console" />
        <PackageReference Include="Hangfire.PostgreSql" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
        <PackageReference Include="Polly" />
        <PackageReference Include="Polly.Extensions.Http" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Migrations\" />
    </ItemGroup>

</Project>
