#!/usr/bin/env bash
#
# Builds an image for every service, or for the services named:
#
#   deploy/build-images.sh                      every service
#   deploy/build-images.sh Orders Billing       only these (the part of the folder name after the product)
#   REGISTRY=registry.example.com TAG=1.4.0 PUSH=1 deploy/build-images.sh
#
# An image is named <REGISTRY>/<product>-<service>:<TAG>, both in lower case with dots as underscores:
# two solutions on one host each get their own orders image. The name is read from the service's own
# deploy files, so a service generated by an earlier version of the template keeps the name its files use. GIT_SHA is the last commit that touched what the image is built from -
# Common, the build props and the service's own folder - so an unchanged service gets the same image
# on every build instead of a new one per commit. Without the build attestation (--provenance=false),
# which carries a timestamp, the digest stays the same too.
set -euo pipefail

cd "$(dirname "$0")/.."

REGISTRY="${REGISTRY:-local}"
TAG="${TAG:-latest}"
PUSH="${PUSH:-0}"
PREFIX="ST.DotNetSolutionKit.Samples."

for project in src/services/*/*.API/*.API.csproj; do
    folder=$(basename "$(dirname "$(dirname "$project")")")
    service="${folder#"$PREFIX"}"

    if [ $# -gt 0 ] && ! printf '%s\n' "$@" | grep -qx "$service"; then
        continue
    fi

    name=""
    for file in "src/services/$folder/deploy/compose.yml" "src/services/$folder/deploy/k8s.yaml"; do
        [ -f "$file" ] || continue
        name=$(sed -n -E 's#^[[:space:]]*image:[[:space:]]*[^/[:space:]]+/([^:[:space:]]+):.*#\1#p' "$file" | head -1)
        [ -n "$name" ] && break
    done
    if [ -z "$name" ]; then
        name="dotnetsolutionkit_samples-$(echo "$service" | tr '[:upper:]' '[:lower:]' | tr '.' '_')"
    fi
    image="$REGISTRY/$name:$TAG"
    sha=$(git log -1 --format=%h -- Directory.Build.props version.json src/Directory.Packages.props src/common "src/services/$folder" 2>/dev/null || true)

    echo "==> $image (commit ${sha:-local})"
    docker build --provenance=false --build-arg SERVICE="$folder" --build-arg GIT_SHA="${sha:-local}" -t "$image" .

    if [ "$PUSH" = "1" ]; then
        docker push "$image"
    fi
done
