#!/usr/bin/env bash
# Part of DotNetSolutionKit (https://dnsk.sawking.tech/). MIT License, Copyright (c) 2025 Vladimir Savkin.
#
#
# Blue-green deployment on one host with docker compose:
#
#   deploy/compose/bluegreen.sh up          start the other color, switch the edge to it, stop the old one
#   deploy/compose/bluegreen.sh rollback    start the previous color again and switch back; nothing is rebuilt
#   deploy/compose/bluegreen.sh status
#
# The services of a color are one compose project, <prefix>-blue or <prefix>-green. PostgreSQL and
# RabbitMQ are a project of their own, shared by both colors: a color reaches them on its own network,
# under their usual names. An nginx edge is the public entry; it proxies to the entry service of the
# active color, and switching colors is one nginx reload.
#
# Settings, from the environment or deploy/compose/.env:
#   ENTRY       the compose service the edge proxies to: the gateway, or the one service; required when
#               the solution has more than one service
#   EDGE_PORT   where the edge listens on the host (8080)
#   EDGE_BIND   the host address it binds (127.0.0.1; 0.0.0.0 to publish it)
#   KEEP_OLD=1  leave the old color running after the switch, for an instant rollback; by default it is
#               stopped, because its jobs and consumers would go on running the old code
#
# Both colors share the database while they overlap: a migration must leave the schema usable by the
# version still running (expand first, remove in a later release).
set -euo pipefail

cd "$(dirname "$0")/../.."

env_file=()
if [ -f deploy/compose/.env ]; then
    env_file=(--env-file deploy/compose/.env)
    set -a; . deploy/compose/.env; set +a
fi

PREFIX="${COMPOSE_PROJECT_NAME:-$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9\n' '-')}"
EDGE_PORT="${EDGE_PORT:-8080}"
EDGE_BIND="${EDGE_BIND:-127.0.0.1}"
STATE=deploy/compose/.bluegreen
ACTIVE_FILE="$STATE/active"
EDGE_DIR="$STATE/edge"
EDGE="$PREFIX-edge"
mkdir -p "$EDGE_DIR"

infra_files=()
for file in deploy/compose/infra/*.yml; do
    [ -e "$file" ] && infra_files+=(-f "$file")
done
service_files=()
for file in src/services/*/deploy/compose.yml; do
    [ -e "$file" ] && service_files+=(-f "$file")
done

infra() { docker compose --project-directory . -p "$PREFIX-infra" "${env_file[@]}" "${infra_files[@]}" "$@"; }
color() { local c=$1; shift; docker compose --project-directory . -p "$PREFIX-$c" "${env_file[@]}" "${service_files[@]}" -f "$STATE/override.yml" "$@"; }
other() { [ "$1" = blue ] && echo green || echo blue; }
active() { cat "$ACTIVE_FILE" 2>/dev/null || true; }

write_override() {
    local services infra_services
    services=$(docker compose --project-directory . "${env_file[@]}" "${infra_files[@]}" "${service_files[@]}" config --services)
    infra_services=$(infra config --services)
    {
        echo "# Generated by bluegreen.sh: a color publishes no ports, depends on no service of its own"
        echo "# project, and runs on a network the script creates and connects the infrastructure to."
        echo "services:"
        for s in $services; do
            grep -qxF -- "$s" <<< "$infra_services" && continue
            printf '  %s:\n    ports: !reset []\n    depends_on: !reset {}\n' "$s"
        done
        printf 'networks:\n  default:\n    name: ${BLUEGREEN_NETWORK}\n    external: true\n'
    } > "$STATE/override.yml"

    if [ -z "${ENTRY:-}" ]; then
        local candidates
        candidates=$(printf '%s\n' $services | grep -vxF -f <(printf '%s\n' $infra_services))
        [ "$(echo "$candidates" | wc -l)" -eq 1 ] || { echo "Set ENTRY to the service the edge proxies to: $(echo $candidates)" >&2; exit 1; }
        ENTRY="$candidates"
    fi
}

prepare_network() {
    local net="$PREFIX-$1"
    docker network inspect "$net" >/dev/null 2>&1 || docker network create "$net" >/dev/null
    for s in $(infra config --services); do
        local id
        id=$(infra ps -q "$s" 2>/dev/null || true)
        [ -n "$id" ] && docker network connect --alias "$s" "$net" "$id" 2>/dev/null || true
    done
}

switch_edge() {
    local c=$1 target="$PREFIX-$1-$ENTRY-1"
    if ! docker inspect "$EDGE" >/dev/null 2>&1; then
        cat > "$EDGE_DIR/default.conf" <<'NGINX'
include /etc/nginx/conf.d/upstream.inc;
server {
    listen 8080;
    location / {
        proxy_pass http://entry;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Prefix "";
    }
}
NGINX
        printf 'upstream entry { server %s:8080; }\n' "$target" > "$EDGE_DIR/upstream.inc"
        docker network inspect "$PREFIX-$c" >/dev/null
        # The folder, not the file, is mounted: a rewritten file is a new inode, which a single-file
        # mount would not see, and nginx would go on reading the old upstream.
        docker run -d --name "$EDGE" --restart unless-stopped --network "$PREFIX-$c" \
            -p "$EDGE_BIND:$EDGE_PORT:8080" -v "$(pwd -W 2>/dev/null || pwd)/$EDGE_DIR:/etc/nginx/conf.d:ro" \
            nginx:1.27-alpine >/dev/null
        return
    fi
    docker network connect "$PREFIX-$c" "$EDGE" 2>/dev/null || true
    printf 'upstream entry { server %s:8080; }\n' "$target" > "$EDGE_DIR/upstream.inc.tmp"
    mv "$EDGE_DIR/upstream.inc.tmp" "$EDGE_DIR/upstream.inc"
    docker exec "$EDGE" nginx -t -q
    docker exec "$EDGE" nginx -s reload
}

# One run at a time: two runs at once would switch the edge and record the active color against each
# other, and the color left recorded could be the one the other run stops. mkdir is atomic everywhere,
# flock is not on every host; a lock left by a run that is gone is taken over.
take_lock() {
    local lock="$STATE/lock" holder
    if mkdir "$lock" 2>/dev/null; then
        echo $$ > "$lock/pid"
        trap 'rm -rf "$STATE/lock"' EXIT
        return
    fi
    holder=$(cat "$lock/pid" 2>/dev/null || true)
    if [ -n "$holder" ] && kill -0 "$holder" 2>/dev/null; then
        echo "Another bluegreen.sh is running (pid $holder)" >&2
        exit 1
    fi
    echo "Taking over the lock of a run that is gone (pid ${holder:-unknown})" >&2
    rm -rf "$lock"
    take_lock
}

# Starts a color and waits for its services to be ready. A color that does not get there is stopped,
# with its last log lines, and the active color is not touched.
start_color() {
    local c=$1; shift
    if BLUEGREEN_NETWORK="$PREFIX-$c" color "$c" up -d --wait "$@"; then
        return 0
    fi
    echo "$c did not become ready; the active color stays as it was" >&2
    BLUEGREEN_NETWORK="$PREFIX-$c" color "$c" logs --tail 30 >&2 || true
    BLUEGREEN_NETWORK="$PREFIX-$c" color "$c" stop >/dev/null 2>&1 || true
    return 1
}

# Points the edge at a color and checks the edge answers. When it does not, the edge goes back to the
# color it served before, if there was one, instead of being left on a color that does not answer.
switch_to() {
    local next=$1 previous=$2
    switch_edge "$next"
    wait_ready && return 0
    if [ -n "$previous" ]; then
        echo "Switching the edge back to $previous" >&2
        switch_edge "$previous"
    fi
    BLUEGREEN_NETWORK="$PREFIX-$next" color "$next" stop >/dev/null 2>&1 || true
    return 1
}

wait_ready() {
    for _ in $(seq 1 30); do
        curl -fsS -o /dev/null "http://127.0.0.1:$EDGE_PORT/ready" && return 0
        sleep 1
    done
    echo "The edge does not answer /ready" >&2
    return 1
}

case "${1:-}" in
    up)
        take_lock
        write_override
        current=$(active); next=$(other "${current:-green}")
        echo "==> infrastructure"
        infra up -d --wait
        # A changed setting or image recreates an infrastructure container, and the new one is on
        # neither color's network: the running color would lose its database. Both are reconnected.
        prepare_network blue
        prepare_network green
        echo "==> $next"
        start_color "$next" || exit 1
        echo "==> edge to $next"
        switch_to "$next" "$current" || exit 1
        echo "$next" > "$ACTIVE_FILE"
        if [ -n "$current" ] && [ "${KEEP_OLD:-0}" != 1 ]; then
            echo "==> stopping $current"
            BLUEGREEN_NETWORK="$PREFIX-$current" color "$current" stop
        fi
        echo "Active: $next"
        ;;
    rollback)
        take_lock
        write_override
        current=$(active); [ -n "$current" ] || { echo "Nothing deployed yet" >&2; exit 1; }
        previous=$(other "$current")
        prepare_network blue
        prepare_network green
        echo "==> $previous"
        start_color "$previous" --no-recreate || exit 1
        switch_to "$previous" "$current" || exit 1
        echo "$previous" > "$ACTIVE_FILE"
        BLUEGREEN_NETWORK="$PREFIX-$current" color "$current" stop
        echo "Active: $previous"
        ;;
    status)
        echo "Active: $(active)"
        docker ps --filter "name=$PREFIX-" --format '{{.Names}}\t{{.Status}}'
        ;;
    *)
        sed -n '3,7p' "$0"
        exit 1
        ;;
esac
