#!/usr/bin/env bash
#
# Blue-green deployment on one host with docker compose:
#
#   deploy/compose/bluegreen.sh up          start the other color, switch the edge to it, stop the old one
#   deploy/compose/bluegreen.sh rollback    start the previous color again and switch back; nothing is rebuilt
#   deploy/compose/bluegreen.sh status
#
# The services of a color are one compose project, <prefix>-blue or <prefix>-green. PostgreSQL and
# RabbitMQ are a project of their own, shared by both colors: a color reaches them on its own network,
# under their usual names. An nginx edge is the public entry; it proxies to the entry service of the
# active color, and switching colors is one nginx reload.
#
# Settings, from the environment or deploy/compose/.env:
#   ENTRY       the compose service the edge proxies to: the gateway, or the one service; required when
#               the solution has more than one service
#   EDGE_PORT   where the edge listens on the host (8080)
#   EDGE_BIND   the host address it binds (127.0.0.1; 0.0.0.0 to publish it)
#   KEEP_OLD=1  leave the old color running after the switch, for an instant rollback; by default it is
#               stopped, because its jobs and consumers would go on running the old code
#
# Both colors share the database while they overlap: a migration must leave the schema usable by the
# version still running (expand first, remove in a later release).
set -euo pipefail

cd "$(dirname "$0")/../.."

env_file=()
if [ -f deploy/compose/.env ]; then
    env_file=(--env-file deploy/compose/.env)
    set -a; . deploy/compose/.env; set +a
fi

PREFIX="${COMPOSE_PROJECT_NAME:-$(basename "$(pwd)" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9\n' '-')}"
EDGE_PORT="${EDGE_PORT:-8080}"
EDGE_BIND="${EDGE_BIND:-127.0.0.1}"
STATE=deploy/compose/.bluegreen
ACTIVE_FILE="$STATE/active"
EDGE_DIR="$STATE/edge"
EDGE="$PREFIX-edge"
mkdir -p "$EDGE_DIR"

service_files=()
for file in src/services/*/deploy/compose.yml; do
    [ -e "$file" ] && service_files+=(-f "$file")
done

infra() { docker compose --project-directory . -p "$PREFIX-infra" "${env_file[@]}" -f deploy/compose/infrastructure.yml "$@"; }
color() { local c=$1; shift; docker compose --project-directory . -p "$PREFIX-$c" "${env_file[@]}" "${service_files[@]}" -f "$STATE/override.yml" "$@"; }
other() { [ "$1" = blue ] && echo green || echo blue; }
active() { cat "$ACTIVE_FILE" 2>/dev/null || true; }

write_override() {
    local services
    services=$(docker compose --project-directory . "${env_file[@]}" -f deploy/compose/infrastructure.yml "${service_files[@]}" config --services)
    {
        echo "# Generated by bluegreen.sh: a color publishes no ports, depends on no service of its own"
        echo "# project, and runs on a network the script creates and connects the infrastructure to."
        echo "services:"
        for s in $services; do
            case "$s" in postgres|rabbitmq|clickhouse|s3|s3-bucket) continue ;; esac
            printf '  %s:\n    ports: !reset []\n    depends_on: !reset {}\n' "$s"
        done
        printf 'networks:\n  default:\n    name: ${BLUEGREEN_NETWORK}\n    external: true\n'
    } > "$STATE/override.yml"

    if [ -z "${ENTRY:-}" ]; then
        local candidates
        candidates=$(printf '%s\n' $services | grep -vx -e postgres -e rabbitmq -e clickhouse -e s3 -e s3-bucket)
        [ "$(echo "$candidates" | wc -l)" -eq 1 ] || { echo "Set ENTRY to the service the edge proxies to: $(echo $candidates)" >&2; exit 1; }
        ENTRY="$candidates"
    fi
}

prepare_network() {
    local net="$PREFIX-$1"
    docker network inspect "$net" >/dev/null 2>&1 || docker network create "$net" >/dev/null
    for s in postgres rabbitmq clickhouse s3; do
        local id
        id=$(infra ps -q "$s" 2>/dev/null || true)
        [ -n "$id" ] && docker network connect --alias "$s" "$net" "$id" 2>/dev/null || true
    done
}

switch_edge() {
    local c=$1 target="$PREFIX-$1-$ENTRY-1"
    if ! docker inspect "$EDGE" >/dev/null 2>&1; then
        cat > "$EDGE_DIR/default.conf" <<'NGINX'
include /etc/nginx/conf.d/upstream.inc;
server {
    listen 8080;
    location / {
        proxy_pass http://entry;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINX
        printf 'upstream entry { server %s:8080; }\n' "$target" > "$EDGE_DIR/upstream.inc"
        docker network inspect "$PREFIX-$c" >/dev/null
        # The folder, not the file, is mounted: a rewritten file is a new inode, which a single-file
        # mount would not see, and nginx would go on reading the old upstream.
        docker run -d --name "$EDGE" --restart unless-stopped --network "$PREFIX-$c" \
            -p "$EDGE_BIND:$EDGE_PORT:8080" -v "$(pwd -W 2>/dev/null || pwd)/$EDGE_DIR:/etc/nginx/conf.d:ro" \
            nginx:1.27-alpine >/dev/null
        return
    fi
    docker network connect "$PREFIX-$c" "$EDGE" 2>/dev/null || true
    printf 'upstream entry { server %s:8080; }\n' "$target" > "$EDGE_DIR/upstream.inc.tmp"
    mv "$EDGE_DIR/upstream.inc.tmp" "$EDGE_DIR/upstream.inc"
    docker exec "$EDGE" nginx -t -q
    docker exec "$EDGE" nginx -s reload
}

wait_ready() {
    for _ in $(seq 1 30); do
        curl -fsS -o /dev/null "http://127.0.0.1:$EDGE_PORT/ready" && return 0
        sleep 1
    done
    echo "The edge does not answer /ready" >&2
    return 1
}

case "${1:-}" in
    up)
        write_override
        current=$(active); next=$(other "${current:-green}")
        echo "==> infrastructure"
        infra up -d --wait
        echo "==> $next"
        prepare_network "$next"
        BLUEGREEN_NETWORK="$PREFIX-$next" color "$next" up -d --wait
        echo "==> edge to $next"
        switch_edge "$next"
        wait_ready
        echo "$next" > "$ACTIVE_FILE"
        if [ -n "$current" ] && [ "${KEEP_OLD:-0}" != 1 ]; then
            echo "==> stopping $current"
            BLUEGREEN_NETWORK="$PREFIX-$current" color "$current" stop
        fi
        echo "Active: $next"
        ;;
    rollback)
        write_override
        current=$(active); [ -n "$current" ] || { echo "Nothing deployed yet" >&2; exit 1; }
        previous=$(other "$current")
        echo "==> $previous"
        BLUEGREEN_NETWORK="$PREFIX-$previous" color "$previous" up -d --wait --no-recreate
        switch_edge "$previous"
        wait_ready
        echo "$previous" > "$ACTIVE_FILE"
        BLUEGREEN_NETWORK="$PREFIX-$current" color "$current" stop
        echo "Active: $previous"
        ;;
    status)
        echo "Active: $(active)"
        docker ps --filter "name=$PREFIX-" --format '{{.Names}}\t{{.Status}}'
        ;;
    *)
        sed -n '3,7p' "$0"
        exit 1
        ;;
esac
